// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewTask struct {
	Text    string  `json:"text"`
	DueDate *string `json:"dueDate,omitempty"`
}

type NewUser struct {
	Name string `json:"name"`
}

type Query struct {
}

type Task struct {
	ID      string  `json:"id"`
	Text    string  `json:"text"`
	Done    bool    `json:"done"`
	DueDate *string `json:"dueDate,omitempty"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
